### ISSUE TITLE
Refactor the landing page inside the new React Workflow

### ISSUE THREAD

**Issue by Renwarren** [PkFokam-Alumni-Network/CommunityWebsite#15]
Our current landing page found here (https://github.com/PkFokam-Alumni-Network/CommunityWebsite/blob/main/index.html) and its [style ](https://github.com/PkFokam-Alumni-Network/CommunityWebsite/blob/main/styles.css) are now obsolete and can be added as part of the React workflow.

**Comment by kouedelo** [comment]
- This has been resolved in the following PR: https://github.com/PkFokam-Alumni-Network/CommunityWebsite/pull/25
