### ISSUE TITLE
Add a logo as a static asset to the project

### ISSUE THREAD

**Issue by Renwarren** [PkFokam-Alumni-Network/CommunityWebsite#2]
- A folder called 'Assets' should be created in the 'src' folder and the logo should be placed in that folder.

**Comment by Dharld** [comment]
I have already added a static image for this one. Can I close this issue @Renwarren ?

**Comment by kouedelo** [comment]
- Ticket issue resolved in following PR: https://github.com/PkFokam-Alumni-Network/CommunityWebsite/pull/25
